services:
  waf:
    image: owasp/modsecurity-crs:4.21.0-nginx-alpine-202512071012
    container_name: waf-proxy
    ports:
      - "80:8080"
    environment:
      - BACKEND=http://frontend:80
      - UPSTREAM_PORT=80
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - MODSECURITY_RULE_ENGINE=On
      - PARANOIA=1
    volumes:
      - ../waf/custom-rules:/etc/nginx/custom-rules:ro
    networks:
      - hm_net
    depends_on:
      frontend:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: postgresql
    cpus: '1.0'
    mem_limit: '1g'
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: always
    networks:
      - hm_net

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    expose:
      - "9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable"
    networks:
      - hm_net
    depends_on:
      - db
    restart: always

  redis:
    image: redis:7.0.15
    container_name: redis
    cpus: '0.5'
    mem_limit: '512m'
    expose:
      - 6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=rediska
    restart: always
    networks:
      - hm_net

  redis_exporter:
    image: oliver006/redis_exporter:latest
    expose:
      - "9121"
    command: ["--redis.addr=redis:6379"]
    # environment:
    #   - REDIS_PASSWORD=rediska
    restart: always
    networks:
      - hm_net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost/api/v1/
        - VITE_WS_BASE_URL=ws://localhost/ws/
    image: hismind-frontend:latest
    cpus: '0.5'
    mem_limit: '512m'
    container_name: hismind-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: always
    networks:
      - hm_net

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: server
    image: hismind-backend:latest
    cpus: '2.0'
    mem_limit: '2g'
    expose:
      - "8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_ENV=settings
      - API_HOST=127.0.0.1
      - API_PORT=80
      - OTEL_PYTHON_LOG_LEVEL=DEBUG
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_SERVICE_NAME=his-mind
      - OTEL_RESOURCE_ATTRIBUTES=service.name=his-mind,service.namespace=sre
    depends_on:
      - db
      - redis
      - tempo
    volumes:
      - global_logs:/var/log/django:rw
    restart: always
    networks:
      - hm_net

  # worker:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #     target: worker
  #   image: hismind-worker:latest
  #   cpus: '1.0'
  #   mem_limit: '1g'
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DJANGO_ENV=settings
  #     - API_HOST=127.0.0.1
  #     - API_PORT=80
  #     - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
  #     - OTEL_TRACES_EXPORTER=otlp
  #     - OTEL_METRICS_EXPORTER=none
  #     - OTEL_LOGS_EXPORTER=none
  #     - OTEL_SERVICE_NAME=his-mind
  #     - OTEL_RESOURCE_ATTRIBUTES=service.name=his-mind,service.namespace=dfir
  #   depends_on:
  #     - db
  #     - redis
  #   volumes:
  #     - global_logs:/var/log/django:ro
  #   restart: always
  #   networks:
  #     - hm_net

  # beat:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #     target: beat
  #   image: hismind-beat:latest
  #   cpus: '1.0'
  #   mem_limit: '1g'
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DJANGO_ENV=settings
  #     - API_HOST=127.0.0.1
  #     - API_PORT=80
  #     - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
  #     - OTEL_ENABLED=true
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
  #     - OTEL_TRACES_EXPORTER=otlp
  #     - OTEL_METRICS_EXPORTER=none
  #     - OTEL_LOGS_EXPORTER=none
  #     - OTEL_SERVICE_NAME=his-mind
  #     - OTEL_RESOURCE_ATTRIBUTES=service.name=his-mind,service.namespace=dfir
  #   depends_on:
  #     - db
  #     - redis
  #     - backend
  #     - worker
  #   volumes:
  #     - global_logs:/var/log/django:ro
  #   restart: always
  #   networks:
  #     - hm_net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    networks:
      - hm_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - hm_net
    depends_on:
      - backend
      - loki
      - promtail

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    user: "0:0"
    volumes:
      - ../loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    restart: always
    networks:
      - hm_net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ../promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - global_logs:/var/log/django:ro
    depends_on:
      - loki
    restart: always
    networks:
      - hm_net

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ../tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo_data:/var/tempo
    expose:
      - "3200"
      - "4317"
      - "4318"
    restart: always
    networks:
      - hm_net

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    restart: always
    networks:
      - hm_net

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    networks:
      - hm_net
    pid: host
    restart: always
    expose: 
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8080
    networks:
      - hm_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  redis_data:
  postgres_data:
  ollama_data:
  loki_data:
  prometheus_data:
  grafana_data:
  tempo_data:
  global_logs:

networks:
  hm_net:
